<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.

$IP = "/home/groups/konfidi/htdocs/w";
ini_set( "include_path", ".:$IP:$IP/includes:$IP/languages" );
require_once( "includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
} elseif ( empty( $wgConfiguring ) ) {
	## Compress output if the browser supports it
	if( !ini_get( 'zlib.output_compression' ) ) @ob_start( 'ob_gzhandler' );
}

$wgSitename         = "Konfidi";

$wgScriptPath	    = "/w";
$wgScript           = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";

## If using PHP as a CGI module, use the ugly URLs
#$wgArticlePath      = "$wgScript/$1";
$wgArticlePath      = "/wiki/$1";
# $wgArticlePath      = "$wgScript?title=$1";

$wgStylePath        = "$wgScriptPath/skins";
$wgStyleDirectory   = "$IP/skins";
$wgLogo             = "$wgStylePath/common/images/wiki.png";

$wgUploadPath       = "$wgScriptPath/images";
$wgUploadDirectory  = "$IP/images";

$wgEmergencyContact = "konfidi-dev@berlios.de";
$wgPasswordSender	= "konfidi-dev@berlios.de";

$wgDBserver         = "db.berlios.de";
$wgDBname           = "konfidi";
$wgDBuser           = "konfidi";
$wgDBprefix         = "mw_";
require_once( "LocalSettings_pwd.php" );

## To allow SQL queries through the wiki's Special:Askaql page,
## uncomment the next lines. THIS IS VERY INSECURE. If you want
## to allow semipublic read-only SQL access for your sysops,
## you should define a MySQL user with limited privileges.
## See MySQL docs: http://www.mysql.com/doc/en/GRANT.html
#
# $wgAllowSysopQueries = true;
# $wgDBsqluser        = "sqluser";
# $wgDBsqlpassword    = "sqlpass";

# If you're on MySQL 3.x, this next line must be FALSE:
$wgDBmysql4 = $wgEnablePersistentLC = false;

## Shared memory settings
$wgUseMemCached = false;
$wgMemCachedServers = array();
#$wgUseTurckShm = function_exists( 'mmcache_get' ) && php_sapi_name() == 'apache';

## To enable image uploads, make sure the 'images' directory
## is writable, then uncomment this:
$wgDisableUploads		= false;
$wgUseImageResize		= true;
# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
# $wgUseTeX			= true;
$wgMathPath         = "{$wgUploadPath}/math";
$wgMathDirectory    = "{$wgUploadDirectory}/math";
$wgTmpDirectory     = "{$wgUploadDirectory}/tmp";

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";
$wgUseLatin1 = false;


$wgProxyKey = "60fd9138748b5b8d8b0e196d6233dd15116c4b518b0b997a7d77f1f3f6280663";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
# $wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = "Konfidi:License"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/by-sa/2.0/";
$wgRightsText = "Attribution-ShareAlike";
$wgRightsIcon = "http://creativecommons.org/images/public/somerights20.gif";
# $wgRightsCode = "by-sa"; # Not yet used

##########
# modifications:
# Entirely disable Anonymous Edits
$wgWhitelistEdit = true;

/** Navigation links for the user sidebar.
 * 'text' is the name of the MediaWiki message that contains the label of this link
 * 'href' is the name of the MediaWiki message that contains the link target of this link.
 *        Link targets starting with http are considered remote links. Ones not starting with
 *        http are considered as names of local wiki pages.
 */
$wgNavigationLinks = array (
	array( 'text'=>'mainpage',	'href'=>'mainpage' ),
	array( 'text'=>'berliosproject',	'href'=>'berlios-project-url' ),
	array( 'text'=>'browsesvn', 'href'=>'svn-url'),
	array( 'text'=>'mailinglists', 'href'=>'mailinglists-url'),
	#array( 'text'=>'portal',	'href'=>'portal-url' ),
	#array( 'text'=>'currentevents', 'href'=>'currentevents-url' ),
	array( 'text'=>'recentchanges', 'href'=>'recentchanges-url' ),
	#array( 'text'=>'randompage',	'href'=>'randompage-url' ),
	#array( 'text'=>'help', 		'href'=>'helppage' ),
	#array( 'text'=>'sitesupport',	'href'=>'sitesupport-url' ),
);
?>
